# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [3]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'
df = pd.read_csv(url, sep = '|')
df.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

### Step 4. Discover what is the mean age per occupation

In [8]:
df.groupby('occupation').age.mean().round(1).sort_values(ascending=False)

occupation
retired          63.1
doctor           43.6
educator         42.0
healthcare       41.6
librarian        40.0
executive        38.7
administrator    38.7
marketing        37.6
lawyer           36.8
engineer         36.4
writer           36.3
salesman         35.7
scientist        35.5
other            34.5
programmer       33.1
technician       33.1
homemaker        32.6
artist           31.4
entertainment    29.2
none             26.6
student          22.1
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [59]:
df_gend = df.groupby(['gender','occupation'])[['user_id']].count().unstack(['gender'])
df_mr = pd.DataFrame(round(df_gend.user_id.M / (df.occupation.value_counts().sort_values()) * 100, 3), columns=['male_ratio'])
df_mr.sort_values('male_ratio', ascending=False)

               male_ratio
occupation
doctor            100.000
engineer           97.015
technician         96.296
retired            92.857
programmer         90.909
executive          90.625
scientist          90.323
entertainment      88.889
lawyer             83.333
salesman           75.000
educator           72.632
student            69.388
other              65.714
marketing          61.538
writer             57.778
none               55.556
administrator      54.430
artist             53.571
librarian          43.137
healthcare         31.250
homemaker          14.286

### Step 6. For each occupation, calculate the minimum and maximum ages

In [60]:
df.groupby('occupation').age.agg(['min','max'])

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [65]:
df.groupby(['occupation','gender']).age.mean().unstack().round(2)

gender             F      M
occupation
administrator  40.64  37.16
artist         30.31  32.33
doctor           NaN  43.57
educator       39.12  43.10
engineer       29.50  36.60
entertainment  31.00  29.00
executive      44.00  38.17
healthcare     39.82  45.40
homemaker      34.17  23.00
lawyer         39.50  36.20
librarian      40.00  40.00
marketing      37.20  37.88
none           36.50  18.60
other          35.47  34.03
programmer     32.17  33.22
retired        70.00  62.54
salesman       27.00  38.56
scientist      28.33  36.32
student        20.75  22.67
technician     38.00  32.96
writer         37.63  35.35

### Step 8.  For each occupation present the percentage of women and men

In [73]:
df_gend['male_ratio'] = round(df_gend.user_id.M/df.occupation.value_counts() * 100, 2)
df_gend['female_ratio'] = round(df_gend.user_id.F/df.occupation.value_counts() * 100, 2)

df_gend

              user_id        male_ratio female_ratio
gender              F      M
occupation
administrator    36.0   43.0      54.43        45.57
artist           13.0   15.0      53.57        46.43
doctor            NaN    7.0     100.00          NaN
educator         26.0   69.0      72.63        27.37
engineer          2.0   65.0      97.01         2.99
entertainment     2.0   16.0      88.89        11.11
executive         3.0   29.0      90.62         9.38
healthcare       11.0    5.0      31.25        68.75
homemaker         6.0    1.0      14.29        85.71
lawyer            2.0   10.0      83.33        16.67
librarian        29.0   22.0      43.14        56.86
marketing        10.0   16.0      61.54        38.46
none              4.0    5.0      55.56        44.44
other            36.0   69.0      65.71        34.29
programmer        6.0   60.0      90.91         9.09
retired           1.0   13.0      92.86         7.14
salesman          3.0    9.0      75.00        25.00
scientist         3.0   28.0      90.32         9.68
student          60.0  136.0      69.39        30.61
technician        1.0   26.0      96.30         3.70
writer           19.0   26.0      57.78        42.22