# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [47]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
df = pd.read_csv(url, sep='\t')

### Step 4. How many products cost more than $10.00?

In [48]:
df['item_price'] = df.item_price.apply(lambda x: float(x[1:]))
df['price_per_item'] = df.item_price / df.quantity
df.query('price_per_item > 10').item_name.nunique()

25

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [53]:
df[['item_name', 'price_per_item']].drop_duplicates().sort_values(['price_per_item'])

                item_name  price_per_item
18            Canned Soda            1.09
34          Bottled Water            1.09
263     Canned Soft Drink            1.25
329         Bottled Water            1.50
6           Side of Chips            1.69
...                   ...             ...
93       Carnitas Burrito           11.75
1963  Carnitas Soft Tacos           11.75
281      Steak Salad Bowl           11.89
1229  Barbacoa Salad Bowl           11.89
1132  Carnitas Salad Bowl           11.89

[139 rows x 2 columns]

### Step 6. Sort by the name of the item

In [55]:
df.sort_values(['item_name'])

,order_id,quantity,item_name,choice_description,item_price,price_per_item
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [76]:
# df.sort_values('price_per_item', ascending=False)
# df[df['price_per_item'] == df.price_per_item.max()]['quantity'].sum()
# df[df['price_per_item'] == df.price_per_item.max()].agg(sum=('quantity','sum'))

df[df['item_price'] == df.item_price.max()]

,order_id,quantity,item_name,choice_description,item_price,price_per_item
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,2.95

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [67]:
df[df['item_name'] == 'Veggie Salad Bowl'].quantity.sum()

18

### Step 9. How many times did someone order more than one Canned Soda?

In [72]:
df[(df['item_name'] == 'Canned Soda') & (df['quantity'] > 1)].order_id.count()

20